name: CLChat
version: '${project.version}'
main: me.frxq15.citylifechat.CityLifeChat
api-version: 1.18
authors: [ Frxq15 ]

commands:
  yell:
    description: yell command
    aliases: [y, yc, yellchat]
  whisper:
    description: whisper command
    aliases: [w]
  global:
    description: global command
    aliases: [g, globalchat, gc]
  twitter:
    description: twitter command
    aliases: [tc, twitterchat]